package com.gdn.x.scheduler.constant;

/**
 * 
 * @author yauritux (yauritux@gmail.com)
 * @version 1.0.0.RC1
 * @since 1.0.0.RC1
 *
 */
public enum Activity {

	CREATED_TASK, ACTIVATED_TASK, SCHEDULED_TASK, 
	MODIFIED_TASK, TERMINATED_TASK,
	CREATED_WORKFLOW, ACTIVATED_WORKFLOW, 
	SCHEDULED_WORKFLOW, MODIFIED_WORKFLOW, TERMINATED_WORKFLOW,
	EXECUTED_PROCESS, TERMINATED_PROCESS, SUSPEND_PROCESS;
}
